### ISSUE TITLE
compare with smile debug toolbar

### ISSUE THREAD

**Issue by onlinebizsoft** [perryholden/Holdenovi_Profiler#3]
Is there some advantages over this one?
https://github.com/Smile-SA/magento2-module-debug-toolbar

**Comment by perryholden** [comment]
@onlinebizsoft - That is a toolbar which displays in the browser window, but this profiler records profiles (runs) in a DB record so that you can view them later in admin and see a hierarchical tree showing time and memory usage. As such, you can keep and view previous profile runs.

The Magento 2 version is based on the old Magento 1 version, which is written about on the original author's blog. It's slightly different, but it should give you a basic idea of what this does: https://fbrnc.net/blog/2012/08/magento-profiler

Closing issue.
